graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET, HEAD, POST, PUT
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true
    max-query-depth: 50
  tools:
   schema-location-pattern: "**/*.graphql"

application:
    name: news
server:
  port: 4114

arango:
  db:
   name: AK-DUMMY
   host: localhost
   port: 8529
   user: root
   password: 8080
   max.connection: 100